name: Catalog Delivery

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: group10-tc-01/fcs-pipelines/.github/workflows/dotnet-service-delivery.yml@main
    with:
      service_name: catalog
      image_name: fcs/catalog-api
      dockerfile_path: src/fcs.Catalog.WebApi/Dockerfile
      docker_context: .
      azure_container_registry_name: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}
      aks_resource_group: ${{ vars.AKS_RESOURCE_GROUP }}
      aks_cluster_name: ${{ vars.AKS_CLUSTER_NAME }}
      k8s_namespace: ${{ vars.K8S_NAMESPACE }}
      k8s_deployment_name: catalog-api
      k8s_container_name: catalog-api
      healthcheck_url: ${{ vars.CATALOG_HEALTHCHECK_URL }}
      environment: production
    secrets: inherit
