apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../08-microservices/fcs-catalog-deployment.yaml
  - ../../../08-microservices/fcs-catalog-service.yaml

images:
  - name: fiapcr.azurecr.io/fcs-catalog
    newName: fiapcr.azurecr.io/fcs-catalog
    newTag: main
